version: '3.4'
services:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'wordpress'
        volumes:
            - 'persistent_db:/var/lib/mysql'
        ports:
            - '3306:3306'
    wordpress:
        build:
            dockerfile: ./Dockerfile-wordpress
        expose:
            - '9000'
        environment:
            WORDPRESS_DB_HOST: 'db'
            WORDPRESS_DB_USER: 'root'
            WORDPRESS_DB_PASSWORD: 'root'
            WORDPRESS_DB_NAME: 'wordpress'
            WORDPRESS_DEBUG: 1
            WORDPRESS_CONFIG_EXTRA: |
                define( 'DISABLE_WP_CRON', true );
                define( 'WP_DEBUG_LOG', '/var/xdebug/wp-errors.log' );
                define( 'FS_DIRECT', true );
                define( 'WP_SITEURL', 'http://webserver:8080' );
                define( 'WP_HOME', 'http://webserver:8080' );
        volumes:
            - './build/wordpress:/var/www/html'
            - './xdebug:/var/xdebug'
            - './config/php.ini:/usr/local/etc/php/conf.d/overrides.ini'
        depends_on:
            - db
    webserver:
        image: nginx:alpine
        ports:
            - '${SERVER_PORT}:8080'
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
            - './build/wordpress:/var/www/html'
        depends_on:
            - 'wordpress'
    nodejs:
        build:
            dockerfile: ./Dockerfile-nodejs
        ports:
            - '3001:3001' # Default port for browserSync UI (for debugging)
            - '${PROXY_PORT}:${PROXY_PORT}'
        env_file:
            - .env
        volumes:
            - './src:/usr/src/app/src'
            - './dist:/usr/src/app/dist'
            - './build:/usr/src/app/build'
            - './backups:/usr/src/app/backups'
        depends_on:
            - 'webserver'
        command: npm run dev
volumes:
    persistent_db:
