name: "Install and Start WordPressify"

env:
  WPFY_GH_REPO: ${{ github.repository }}
  WPFY_GH_REF: ${{ github.ref }}

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci --no-audit
      - run: ./installer/index.js -y
